'use client';
import {useEffect,useState} from 'react';
import {ExternalLink} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogClose} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {type ReputationReport,baseline,evidenceGroups} from '@/lib/reputation';
import {recentReport} from '@/lib/reputation-recent';
const dateLabel=(date:string)=>new Date(date).toLocaleDateString('bg-BG',{timeZone:'Europe/Sofia',day:'numeric',month:'short',year:'numeric'});
type Topic=ReputationReport['topics'][number];
const compact:Record<string,{focus:string;note:string;action:string}>={
 'Чистота':{focus:'Варовик и остатъци от сапун в банята.',note:'Две забележки; има и много похвали.',action:'Контрол след почистване на баните.'},
 'Закуска':{focus:'Разнообразие и представяне.',note:'Две забележки; други гости хвалят закуската.',action:'Преглед на менюто, порциите и зеленчуците.'},
 'Интернет':{focus:'Wi-Fi: 7,5 / 10 в Booking.',note:'Няма конкретно скорошно оплакване в прочетените текстове.',action:'Измери скоростта и покритието в стаите.'},
 'Обслужване и комфорт':{focus:'Топло отношение и удобни стаи.',note:'Положителни мнения в Google и Booking.',action:'Запази личното отношение.'},
 'Шум и комарници':{focus:'Вечерен шум; стар сигнал за комарник.',note:'Комарникът е споменат през 2025 г. — може вече да е решено.',action:'Провери шумоизолацията и комарниците.'}
};
function shorten(text:string,max=130){if(text.length<=max)return text;const first=text.match(/^.*?[.!?](?:\s|$)/)?.[0]?.trim();if(first&&first.length<=max)return first;return text.slice(0,max).replace(/\s+\S*$/,'')+'…';}
export function Reputation(){
 const [reports,setReports]=useState<ReputationReport[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[topic,setTopic]=useState<Topic|null>(null),[platform,setPlatform]=useState<'google'|'booking'|null>(null);
 async function load(){setLoading(true);setError('');try{const response=await fetch('/api/reputation',{cache:'no-store'});const data=await response.json() as {error?:string;reports?:ReputationReport[]};if(!response.ok||!data.reports)throw Error(data.error||'Неуспешно зареждане.');const loaded=data.reports;setReports(loaded);setSelected(s=>s||loaded[0]?.id||'');}catch(e){setError(e instanceof Error?e.message:'Неуспешно зареждане.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const report=reports.find(r=>r.id===selected)??reports[0]??recentReport;
 const displayedReports=reports.length?reports:[recentReport];
 const source=report.sources.find(s=>s.platform===platform);
 const points=[...displayedReports].reverse().filter(r=>r.sources.some(s=>s.platform===platform&&s.status!=='unavailable'&&s.rating!==null)).map(r=>({date:dateLabel(r.observedAt),rating:r.sources.find(s=>s.platform===platform)!.rating}));
 const rank={attention:0,unknown:1,positive:2};
 const groups=topic?evidenceGroups(topic):{negative:[],positive:[],other:[]};
 const topics=[...report.topics].sort((a,b)=>rank[a.status]-rank[b.status]);
 return <section className="reputation reputation-compact">
  <div className="reputation-toolbar"><span>Последна актуализация на данните: {dateLabel(report.observedAt)} · {report.sources.some(s=>s.status!=='complete')?'Частичен анализ':'Потвърдена извадка'}</span><div>{reports.length>1&&<label>Преглед<select value={report.id} onChange={e=>{setSelected(e.target.value);setTopic(null);setPlatform(null);}}>{reports.map(r=><option key={r.id} value={r.id}>{dateLabel(r.observedAt)} · {r.analysisMode==='latest25'?'Последни 25':'Стара извадка'}</option>)}</select></label>}</div></div>
  <p className="reputation-footnote">За обновяване на данните отворете разговора с ChatGPT за това приложение и поискайте актуализация. Данните не се обновяват автоматично.</p>
  {error&&<p className="error-banner" role="alert">{error} Показан е последният вграден преглед.</p>}
  <div className="reputation-scores">{report.sources.map(s=><article className="reputation-card reputation-score-card" key={s.platform}><div><h2>{s.platform==='google'?'Google Maps':'Booking'}</h2><p className="reputation-score">{s.rating?.toLocaleString('bg-BG')??'—'}<span> / {s.platform==='google'?5:10}</span></p><span className="reputation-meta">{s.total??'Неизвестен брой'} оценки</span></div><button className="secondary" onClick={()=>setPlatform(s.platform)}>История и обхват</button></article>)}</div>
  <section className="reputation-card reputation-table-card"><div className="reputation-card-heading"><h2>Върху какво да работим</h2><span>Първо — проблемите за проверка</span></div>
   <div className="reputation-scope">{report.analysisMode==='latest25'?<><strong>Анализ само на последните 25 отзива от всяка платформа, по дата.</strong>{report.sources.map(s=><p key={s.platform}><b>{s.platform==='google'?'Google':'Booking'}:</b> {s.window?.verified?<>{s.reviewed} оценки · {s.window.textCount} с текст · {s.window.from&&dateLabel(s.window.from+'T12:00:00Z')}–{s.window.to&&dateLabel(s.window.to+'T12:00:00Z')}</>:<>Последните 25 не са достъпни за потвърждение. Коментарите не участват в анализа.</>}</p>)}<small>Проблемите са изведени само от текстовете в тази извадка. Общите оценки отгоре са за целия профил.</small></>:<><strong>Архивен анализ по старата извадка.</strong><p>Този преглед не е ограничен до последните 25 отзива.</p></>}</div><Table className="reputation-table"><TableHeader><TableRow><TableHead>Тема</TableHead><TableHead>Накратко</TableHead><TableHead>Следваща стъпка</TableHead><TableHead><span className="sr-only">Мнения и подробности</span></TableHead></TableRow></TableHeader><TableBody>{topics.map(t=>{
    const short=report.id===baseline.id?compact[t.name]:undefined;
    const grouped=evidenceGroups(t);const count=t.status==='positive'?grouped.positive.length:grouped.negative.length;const label=count?(t.status==='positive'?'Виж похвалите':'Виж забележките'):'Детайли';
    return <TableRow key={t.name}><TableCell><strong>{t.name}</strong><span className={`reputation-status ${t.status}`}>{t.status==='attention'?'За проверка':t.status==='positive'?'Добре':'Нужни са данни'}</span></TableCell><TableCell><strong className="reputation-focus">{short?.focus??shorten(t.finding)}</strong>{short&&<span className="reputation-row-note">{short.note}</span>}</TableCell><TableCell>{short?.action??shorten(t.action,100)}</TableCell><TableCell><button className="secondary" aria-label={`${label}: ${t.name}`} onClick={()=>setTopic(t)}>{count?`${label} (${count})`:label}</button></TableCell></TableRow>;
   })}</TableBody></Table>
  </section>
  <p className="reputation-footnote">Автоматичното седмично обновяване още не е активно. Обобщението се основава на достъпните отзиви.</p>
  <Dialog open={!!topic} onOpenChange={open=>{if(!open)setTopic(null);}}><DialogContent className="reputation-dialog" showCloseButton={false}><DialogHeader><DialogTitle>{topic?.name}</DialogTitle><DialogDescription>{report.analysisMode==='latest25'?'Примери само от потвърдената извадка на последните 25 оценки по дата.':'Примери от архивната извадка.'} Кратки преразкази, не дословни цитати.</DialogDescription></DialogHeader>{topic&&<><div className="reputation-dialog-summary"><strong>Извод</strong><p>{topic.finding}</p><strong>Какво да направим</strong><p>{topic.action}</p></div><section><h3>{topic.status==='positive'?'Положителни мнения':'Забележки'}</h3>{(topic.status==='positive'?groups.positive:groups.negative).length?<ul className="reputation-evidence">{(topic.status==='positive'?groups.positive:groups.negative).map((item,i)=><li key={i}><strong>{item.platform==='google'?'Google':'Booking'} · {item.reviewer} · {item.date}</strong><p>{item.summary}</p></li>)}</ul>:<p>Няма конкретни забележки за тази тема в прочетената извадка.</p>}</section>{topic.status!=='positive'&&groups.positive.length>0&&<details className="reputation-positive-details"><summary>Положителни мнения ({groups.positive.length})</summary><ul className="reputation-evidence">{groups.positive.map((item,i)=><li key={i}><strong>{item.platform==='google'?'Google':'Booking'} · {item.reviewer} · {item.date}</strong><p>{item.summary}</p></li>)}</ul></details>}{groups.other.length>0&&<details className="reputation-positive-details"><summary>Други мнения · без потвърдена класификация ({groups.other.length})</summary><ul className="reputation-evidence">{groups.other.map((item,i)=><li key={i}><strong>{item.platform==='google'?'Google':'Booking'} · {item.reviewer} · {item.date}</strong><p>{item.summary}</p></li>)}</ul></details>}</>}<DialogClose asChild><button className="secondary reputation-dialog-close">Затвори</button></DialogClose></DialogContent></Dialog>
  <Dialog open={!!platform} onOpenChange={open=>{if(!open)setPlatform(null);}}><DialogContent className="reputation-dialog" showCloseButton={false}><DialogHeader><DialogTitle>{platform==='google'?'Google Maps':'Booking'} · История и обхват</DialogTitle><DialogDescription>Проверено на {dateLabel(report.observedAt)}. {source?.status==='complete'?'Потвърдена извадка':source?.status==='unavailable'?'Недостъпен източник':'Частичен преглед'}.</DialogDescription></DialogHeader>{source&&<><p><strong>Прегледани: {source.reviewed} от {source.total??'неизвестен брой'} оценки.</strong></p><p>{source.note}</p><a className="reputation-link" href={source.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/> Отвори източника</a><div className="reputation-chart"><h3>Обща оценка във времето</h3>{points.length>=2?<ResponsiveContainer width="100%" height={210}><LineChart data={points}><XAxis dataKey="date" tick={{fontSize:14}}/><YAxis domain={[0,platform==='google'?5:10]} tick={{fontSize:14}}/><Tooltip/><Line dataKey="rating" name="Оценка" stroke="#176197" strokeWidth={3} dot connectNulls={false}/></LineChart></ResponsiveContainer>:<p>Имаме едно измерване. Нужно е още едно успешно измерване за графика на промяната.</p>}</div></>}<DialogClose asChild><button className="secondary reputation-dialog-close">Затвори</button></DialogClose></DialogContent></Dialog>
 </section>;
}
