import {z} from 'zod';
import {rankingSchema} from './hotel-ranking';
const reviewWindow=z.object({target:z.literal(25),order:z.literal('newest'),verified:z.boolean(),textCount:z.number().int().min(0).max(25),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable()});
const source = z.object({platform:z.enum(['google','booking']),url:z.string().url().refine(v=>{const h=new URL(v).hostname;return h==='www.google.com'||h==='www.booking.com';}),rating:z.number().nullable(),total:z.number().int().nonnegative().nullable(),reviewed:z.number().int().nonnegative(),status:z.enum(['partial','complete','unavailable']),note:z.string().max(1500),window:reviewWindow.optional()}).superRefine((v,c)=>{if(v.rating!==null&&(v.rating<0||v.rating>(v.platform==='google'?5:10)))c.addIssue({code:'custom',message:'Оценката е извън скалата.'});if(v.total!==null&&v.reviewed>v.total)c.addIssue({code:'custom',message:'Броят прочетени отзиви надвишава общия брой.'});if(v.status==='unavailable'&&v.reviewed!==0)c.addIssue({code:'custom',message:'Недостъпният източник не може да има прочетени отзиви.'});});
export const reportSchema=z.object({ranking:rankingSchema.optional(),analysisMode:z.literal('latest25').optional(),id:z.string().min(1).max(100),observedAt:z.string().datetime(),summary:z.string().min(1).max(4000),sources:z.array(source).length(2).refine(a=>new Set(a.map(s=>s.platform)).size===2),topics:z.array(z.object({name:z.string().max(100),status:z.enum(['attention','positive','unknown']),finding:z.string().max(2000),action:z.string().max(1000),evidence:z.array(z.object({platform:z.enum(['google','booking']),reviewer:z.string().max(100),date:z.string().max(100),summary:z.string().max(1000),sentiment:z.enum(['negative','positive','neutral']).optional()})).max(20)})).max(12)}).superRefine((report,ctx)=>{if(report.analysisMode!=='latest25')return;for(const source of report.sources){if(source.reviewed>25||source.window&&source.window.textCount>source.reviewed)ctx.addIssue({code:'custom',message:'Невалиден размер на извадката.'});if(source.window?.verified&&(!source.window.from||!source.window.to||source.window.from>source.window.to))ctx.addIssue({code:'custom',message:'Липсва валиден период.'});}for(const topic of report.topics)for(const item of topic.evidence){const window=report.sources.find(source=>source.platform===item.platform)?.window;const parts=item.date.match(/^(\d{2})\.(\d{2})\.(\d{4})$/);const day=parts?`${parts[3]}-${parts[2]}-${parts[1]}`:'';if(!window?.verified||!day||!window.from||!window.to||day<window.from||day>window.to)ctx.addIssue({code:'custom',message:'Примерът не е в потвърдената извадка от най-новите отзиви.'});}});
export type ReputationReport=z.infer<typeof reportSchema>;
export const baseline:ReputationReport={
 id:'initial-2026-10-05',observedAt:'2026-10-05T16:50:00.000Z',
 summary:'Общата оценка е много висока. Достъпните отзиви често хвалят отношението, просторните стаи и близостта до плажа. В Booking има две конкретни забележки за чистота и закуска; те заслужават проверка, въпреки многото положителни мнения. Wi-Fi е най-слабо оценената категория (7,5/10), но в прочетената извадка няма конкретен скорошен коментар за бавен интернет. Това е първи частичен преглед, а не тенденция или доказателство за текущото състояние.',
 sources:[
 {platform:'google',url:'https://www.google.com/maps/place/Maria+Garden/data=!4m2!3m1!1s0x40a4fdb9c5922a8b:0x1349b7d406c821c0',rating:4.9,total:81,reviewed:5,status:'partial',note:'Публичната страница показва 81 оценки: 74 с пет звезди и 7 с четири. Достъпни са 5 коментара; останалите изискват вход в тази браузърна сесия. Част от текстовете са съкратени. Относителните дати са запазени както се показват.'},
 {platform:'booking',url:'https://www.booking.com/hotel/bg/mariia-gardn.bg.html',rating:9.4,total:157,reviewed:19,status:'partial',note:'Прочетени са 10 най-подходящи и 10 най-нови отзива, с един общ запис: 19 уникални оценки. Четири нямат текст. Най-новият видян отзив е от 26.09.2026. Категории: чистота 9,4; персонал 9,8; комфорт 9,6; Wi-Fi 7,5.'}],
 topics:[
 {name:'Чистота',status:'attention',finding:'Повечето прочетени мнения са положителни, но две оценки от края на август и началото на септември съдържат конкретни забележки. Това не доказва общ спад.',action:'Провери премахването на варовик и сапунени остатъци в баните и контрола след почистване.',evidence:[{sentiment:'negative',platform:'booking',reviewer:'Автор 2',date:'30.08.2026',summary:'Като цяло чисто, но с варовик по душа и сапунени остатъци по рафтчетата.'},{sentiment:'negative',platform:'booking',reviewer:'Автор 1',date:'05.09.2026',summary:'Недоволство от чистотата и поддръжката на вилата и градината.'}]},
 {name:'Закуска',status:'attention',finding:'Има както похвали за разнообразие и домашно приготвена храна, така и две забележки за представянето и ограниченото меню.',action:'Прегледай порциите, представянето, измиването на зеленчуците и разнообразието по дни.',evidence:[{sentiment:'negative',platform:'booking',reviewer:'Автор 1',date:'05.09.2026',summary:'Смята закуската за слаба и дава примери от два дни.'},{sentiment:'negative',platform:'booking',reviewer:'Автор 2',date:'30.08.2026',summary:'Закуската е добра, но представянето и почистването на зеленчуците имат нужда от подобрение.'},{sentiment:'positive',platform:'booking',reviewer:'Автор 5',date:'27.08.2026',summary:'Хвали различната закуска всеки ден, пресните плодове и домашните ястия.'}]},
 {name:'Интернет',status:'unknown',finding:'Booking показва Wi-Fi 7,5/10. В прочетените текстове не е установено конкретно актуално оплакване от скоростта.',action:'Измери скоростта и покритието в стаите при натоварване; ниската категория е сигнал за проверка, а не диагноза.',evidence:[]},
 {name:'Обслужване и комфорт',status:'positive',finding:'Отзиви от двете платформи хвалят топлото отношение, удобните стаи и близостта до плажа.',action:'Запази личното отношение и бързата реакция при проблеми.',evidence:[{sentiment:'positive',platform:'booking',reviewer:'Автор 10',date:'27.08.2026',summary:'Силно положително мнение за гостоприемството и индивидуалното внимание.'},{sentiment:'positive',platform:'google',reviewer:'Автор 14',date:'преди 2 месеца',summary:'Хвали топлото отношение, чистотата и домашния уют.'},{sentiment:'positive',platform:'google',reviewer:'Автор 15',date:'преди 2 години',summary:'Хвали чистите стаи, удобните легла, домакините и близостта до плажа.'}]},
 {name:'Шум и комарници',status:'attention',finding:'Един отзив посочва вечерен шум от близката зона за развлечения. По-стар отзив от 2025 г. споменава липсващ комарник.',action:'Провери шумоизолацията и актуалното наличие на комарници; старият сигнал може вече да е решен.',evidence:[{sentiment:'negative',platform:'booking',reviewer:'Автор 5',date:'27.08.2026',summary:'Вечерният шум налага затваряне на прозорците.'},{sentiment:'negative',platform:'booking',reviewer:'Автор 16',date:'04.09.2025',summary:'Комари и липсващ комарник на балконската врата; хотелът обещава поставяне през следващата година.'}]}
 ]
};

export function evidenceGroups(topic:ReputationReport['topics'][number]){return {negative:topic.evidence.filter(item=>item.sentiment==='negative'),positive:topic.evidence.filter(item=>item.sentiment==='positive'),other:topic.evidence.filter(item=>item.sentiment!=='negative'&&item.sentiment!=='positive')};}
